plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.abramyan.watch'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.abramyan.watch'
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
